name: CICD

on:
  push:
    branches: [master]

jobs:
  test-deploy:
    runs-on: macos-latest # because linux generates different snapshots with puppeteer
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*') }}
          restore-keys: ${{ runner.os }}-deno-
          path: |
            /Users/runner/hostedtoolcache/deno
            /Users/runner/Library/Caches/deno/deno_puppeteer/chromium
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: fetch any uncached dependencies
        run: deno cache main.ts
      - continue-on-error: true
        run: deno lint
      - continue-on-error: true
        run: deno fmt --check
      - run: deno task install-puppeteer
      - run: deno task make-env
      - run: deno test --allow-all
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: snapshots
          path: test/__snapshots__
      - uses: denoland/deployctl@v1
        with:
          project: "bkosm"
          entrypoint: "./main.ts"
          import-map: "./import_map.json"
