name: CICD

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*') }}
          restore-keys: ${{ runner.os }}-deno-
          path: |
            /home/runner/.deno
            /home/runner/.cache/deno
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      # this has no effect for now, as a docker image is built on every run
      # - name: fetch any uncached dependencies
      #   run: deno cache main.ts
      - continue-on-error: true
        run: deno lint
      - continue-on-error: true
        run: deno fmt --check
      - run: deno task install-puppeteer
      - uses: isbang/compose-action@v1.1.0
      - run: IS_PIPELINE=true deno test --allow-all
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: snapshots
          path: test/snapshots
